### ISSUE TITLE
Python error message version 2.6 mac os x

### ISSUE THREAD

**Issue by emanzo** [enricofer/undoPropertiesChanges#1]
Errore durante l'esecuzione di codice Python:

Traceback (most recent call last):
  File "/Users/emilianomanzo/.qgis2/python/plugins/undoPropertiesChanges/undopropertieschanges.py", line 267, in currentLayerChanges
    if self.undo[layer.id()].isEmpty():
KeyError: u'Db_APO_13_100_dic201320141113112339992'

Versione Python:
2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

Versione di QGIS:
2.6.0-Brighton Brighton, 

Percorso Python: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Users/emilianomanzo/.qgis2/python/plugins/sextante_animove', '/Users/emilianomanzo/.qgis2/python/plugins/processinglwgeomprovider', '/Users/emilianomanzo/.qgis2/python/plugins/GeoCoding', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/emilianomanzo/.qgis2/python', u'/Users/emilianomanzo/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/B/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Library/Frameworks/cairo.framework/Versions/1/Python/2.7', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/PIL', '/Users/emilianomanzo/.qgis2/python/plugins/MetaSearch/ext-libs', '/usr/share/qgis/python', '~/.qgis/python', '.', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools']

**Comment by enricofer** [comment]
issue fixed. Please update plugin.
https://plugins.qgis.org/plugins/undoPropertiesChanges/version/1.1/
